### ISSUE TITLE
confusion with working directory when debugging in Visual Studio

### ISSUE THREAD

**Issue by RallyTronics** [Equilibrium-Games/Flounder#4]
When I try to execute the ExampleStarting project in the Flounder.sln solution from the Build folder the working directory is Flounder/Build/Sources/ExampleStarting  I don't see a way to tell it that the resources are up a few directory levels.  How do you typically handle this when running in the debugger?

**Comment by mattparks** [comment]
What I do is I create a symlink from the main Resources folder to the executable output directory (VS puts it into Build\Release\bin\Debug\) so that the executable can run properly. I have had a lot of issues with debugging Visual Studios where it will crash on runtime (release mode works). But debugging on CLion has always worked for me.

**Comment by RallyTronics** [comment]
That did the trick, thanks!
